<Project>
  <PropertyGroup>
    <Authors>최노아(Noah-Choi);OpenVisionLab</Authors>
    <Company>OpenVisionLab</Company>
    <Copyright>Copyright (c) 2026 최노아(Noah-Choi)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>2.7.1</Version>
    <PackageVersion>2.7.1</PackageVersion>
    <RepositoryType>git</RepositoryType>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts\packages</PackageOutputPath>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)NOTICE" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
