<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OpenCvSharp">
      <HintPath>..\Lib.Common\DLL\OpenCvSharp.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <None Include="..\Lib.Common\DLL\OpenCvSharpExtern.dll">
      <Link>OpenCvSharpExtern.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lib.Inspection\Lib.Inspection.csproj" />
  </ItemGroup>

</Project>
